name: foodninja
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  image_picker: ^1.0.7
  google_fonts: ^6.1.0
  get_it: ^7.6.0
  geolocator: ^10.1.0
  hive: ^2.2.3
  path_provider: ^2.0.15
  mask_text_input_formatter: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

